name: Alpha Build
on:
    workflow_dispatch:
    push:
        branches:
            - master
            - dev
            - "feat/*"
        paths-ignore:
            - ".gitattributes"
            # - ".github/**"
            - ".gitignore"
            - ".gitmodules"
            - "**.md"
            - "LICENSE"
            - "server/**"
    pull_request:
        branches:
            - dev
        paths-ignore:
            - ".gitattributes"
            - ".github/**"
            - ".gitignore"
            - ".gitmodules"
            - "**.md"
            - "LICENSE"

jobs:
    build:
        runs-on: windows-latest
        env:
            OPENCV_VERSION: "4.9.0"
            OPENCV_DIR: C:\opencv\build
            OPENCV_INCLUDE_PATHS: C:\opencv\build\include
            OPENCV_LINK_LIBS: opencv_world490
            OPENCV_LINK_PATHS: C:\opencv\build\x64\vc16\lib
            LIBCLANG_PATH: C:\Program Files\LLVM\bin
            OPENCV_BIN_PATHS: C:\opencv\build\x64\vc16\bin
        # strategy:
        #   matrix:
        #     node-version: [18.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js LTS
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  cache: true

            - name: Cache vcpkg
              uses: actions/cache@v3
              with:
                  path: |
                      ./vcpkg/installed
                      ./vcpkg/packages
                      ./vcpkg/vcpkg-binarycache
                  key: ${{ runner.os }}-vcpkg-${{ hashFiles('./vcpkg/vcpkg.json') }}
                  restore-keys: |
                      ${{ runner.os }}-vcpkg-

            - name: Install LLVM
              run: choco install llvm -y

            - name: Set up OpenCV
              run: |
                  $version = "${{ env.OPENCV_VERSION }}"
                  $url = "https://github.com/opencv/opencv/releases/download/$version/opencv-$version-windows.exe"
                  Invoke-WebRequest -Uri $url -OutFile "opencv.exe"
                  7z x opencv.exe -oC:\ -y
                  Remove-Item opencv.exe
                  "C:\opencv\build\x64\vc16\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
                  "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

            - name: Verify LLVM installation
              run: |
                  clang --version
                  echo "LLVM installed successfully"

            - name: Verify OpenCV installation
              run: |
                  dir "C:\opencv\build\x64\vc16\lib"
                  echo "OpenCV installed successfully"

            - name: Build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              run: |
                  pnpm install
                  pnpm run tb

            - name: Upload artifact
              if: success() && github.event_name != 'pull_request'
              uses: actions/upload-artifact@v4
              with:
                  name: dna-builder-alpha-${{ github.sha }}
                  path: ${{ github.workspace }}/src-tauri/target/release/DNA Builder.exe

            - name: Add summary
              if: success() && github.event_name != 'pull_request'
              shell: pwsh
              run: |
                  $summary = "
                  > [!WARNING]
                  > 该版本是由 CI 程序自动打包生成的 `Alpha` 测试版本，**仅供开发者测试使用**

                  > [!TIP]
                  > 普通用户请 [点击这里](https://github.com/pa001024/dna-builder/releases/latest/) 下载最新的稳定版本
                  "

                  echo $summary >> $Env:GITHUB_STEP_SUMMARY
